export const SPECIES_ICON: Record<string, string> = {
  "royal-bengal-tiger": "🐅",
  "asiatic-lion": "🦁",
  "indian-rhinoceros": "🦏",
  "asian-elephant": "🐘",
  "lion-tailed-macaque": "🐒",
  "great-indian-bustard": "🦅",
  "barasingha": "🦌",
  "indian-giant-squirrel": "🐿️",
  "indian-eagle-owl": "🦉",
  "indian-peafowl": "🦚",
  "narcondam-hornbill": "🐦",
  "nicobar-long-tailed-macaque": "🐒",
  "snow-leopard": "🐆",
  "sloth-bear": "🐻",
  "indian-leopard": "🐆",
  "cheetah": "🐾",
  "nilgiri-tahr": "🦌",
  "sangai": "🦌",
  "red-panda": "🐾",
  "gaur": "🐾",
  "hoolock-gibbon": "🐒",
  "clouded-leopard": "🐆",
  "blackbuck": "🐾",
  "chital": "🐾",
  "sambar-deer": "🦌",
  "hangul": "🐾",
  "dhole": "🐾",
  "indian-gray-wolf": "🐾",
  "golden-jackal": "🐾",
  "striped-hyena": "🐾",
  "nilgai": "🐾",
  "chinkara": "🐾",
  "indian-wild-ass": "🐾",
  "wild-water-buffalo": "🐾",
  "great-hornbill": "🐦",
  "himalayan-monal": "🦅",
  "sarus-crane": "🦩",
  "greater-flamingo": "🦩",
  "house-sparrow": "🐦",
  "black-necked-crane": "🦩",
  "malabar-pied-hornbill": "🐦",
  "indian-vulture": "🦅",
  "forest-owlet": "🦉",
  "painted-stork": "🦩",
  "bar-headed-goose": "🦅",
  "indian-roller": "🐦",
  "house-crow": "🐦",
  "malabar-whistling-thrush": "🐦",
  "indian-pitta": "🐦",
};

export const DEFAULT_SPECIES_ICON = "🐾";

export const PROTECTED_AREA_ICON: Record<string, string> = {
  "national-park": "🌲",
  "wildlife-sanctuary": "🏕️",
  "bird-sanctuary": "🪶",
};

export const ZOO_ICON = "🏛️";
